name: Create Bump Pull Request

permissions:
  # Allows us write to the repo
  contents: write
  # Actions permission allows us create pull requests.
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Ockam tag to update terrform version to. e.g. ockam_v0.59.0
        required: true
      branch_name:
        description: New Branch To Bump Crates
        required: true

jobs:
  create_pull_request:
    name: Create Pull Request
    runs-on: ubuntu-20.04
    environment: release
    container:
      image: ghcr.io/build-trust/ockam-builder@sha256:a04b6a0aa01a93ba9a5c67392872893b261772dedfcd58f72a1addacf7535c09
    steps:
      - name: Checkout Terraform Repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0

      - name: Import GPG key
        id: import_gpg
        uses: hashicorp/ghaction-import-gpg@78437f97569a473e42b227be84d4084c2dfb49ba
        env:
          GPG_PRIVATE_KEY: '${{ secrets.PR_BOT_GPG_PRIVATE_KEY }}'
          PASSPHRASE: '${{ secrets.PR_BOT_GPG_PASSPHRASE }}'

      - name: Add GPG Key
        run: |
          git config --global user.email "${{ secrets.PR_BOT_EMAIL }}"
          git config --global user.name "${{ secrets.PR_BOT_GITHUB_USERNAME }}"
          git config --global user.signingkey "${{ steps.import_gpg.outputs.fingerprint }}"

      - name: Create New Branch
        run: git checkout -B ${{ github.event.inputs.branch_name }}

      - name: Bump Terraform Version
        shell: bash
        run: |
          set -x
          tag_name="${{ github.event.inputs.tag }}"
          version_number=${tag_name:7}

          temp_dir=$(mktemp -d)
          cp .github/constants.go.template $temp_dir/constants.go
          cd $temp_dir

          sed -i "s/ockam_version/$version_number/g" constants.go

          cp constants.go $GITHUB_WORKSPACE/internal/provider/constants.go
          cat $GITHUB_WORKSPACE/internal/provider/constants.go

      - name: Create Pull Request
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add $GITHUB_WORKSPACE/internal/provider/constants.go
          git commit -S -m "Update version number"
          git push --set-upstream origin ${{ github.event.inputs.branch_name }}

          tag_name="${{ github.event.inputs.tag }}"
          version=${tag_name:6}

          git tag -s $version -m "Ockam Release"
          git push --tags
