name: Release Binaries

permissions:
  # Allows us write to the repo
  contents: write

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Ockam tag to update terrform version to. e.g. ockam_v0.59.0
        required: true

jobs:
  # Should be ran after Pull request has been merged
  create_release:
    name: Create Release
    runs-on: ubuntu-20.04
    environment: release
    steps:
      - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923
        with:
          go-version: 1.18

      - name: Create Release Context
        id: release
        run: |
          tag_name="${{ github.event.inputs.tag }}"
          version=${tag_name:6}

          echo ::set-output name=version::$version

      - name: Checkout Terraform Repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0
          ref: ${{ steps.release.outputs.version }}

      - name: Import GPG key
        uses: build-trust/.github/actions/import_gpg@custom-actions
        id: release_gpg
        with:
          gpg_private_key: '${{ secrets.RELEASE_GPG_PRIVATE_KEY }}'
          gpg_password: '${{ secrets.RELEASE_GPG_PASSPHRASE }}'
          gpg_name: '${{ secrets.RELEASE_BOT_GITHUB_USERNAME }}'
          gpg_email: '${{ secrets.RELEASE_BOT_EMAIL }}'

      - name: Create GitHub release
        id: release_upload_url
        uses: actions/create-release@4c11c9fe1dcd9636620a16455165783b20fc7ea0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: '${{ steps.release.outputs.version }}'
          tag_name: '${{ steps.release.outputs.version }}'
          body: 'Ockam Terraform Provider - ${{ steps.release.outputs.version }}'

      - uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - run: go mod download

      - uses: goreleaser/goreleaser-action@68acf3b1adf004ac9c2f0a4259e85c5f66e99bef # v2.9.1
        with:
          version: latest
          args: release --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.release_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
