name: Release Binaries

permissions:
  # Allows us write to the repo
  contents: write

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Ockam tag to update terrform version to. e.g. ockam_v0.59.0
        required: true

jobs:
  # Should be ran after Pull request has been merged
  create_release:
    name: Create Release
    runs-on: ubuntu-20.04
    environment: release
    steps:
      - name: Checkout Terraform Repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0

      - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923
        with:
          go-version: 1.18

      - name: Create Release Context
        id: release
        run: |
          tag_name="${{ github.event.inputs.tag }}"
          version=${tag_name:6}

          echo ::set-output name=version::$version

      - name: Create GitHub release
        id: release_upload_url
        uses: actions/create-release@4c11c9fe1dcd9636620a16455165783b20fc7ea0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: '${{ steps.release.outputs.version }}'
          tag_name: '${{ steps.release.outputs.version }}'
          body: 'Ockam Terraform Provider - ${{ steps.release.outputs.version }}'
          draft: true

      - name: Fetch Recently Created Tag
        run: |
          git pull
          git fetch --tags

      - uses: actions/cache@48af2dc4a9e8278b89d7fa154b955c30c6aaab09
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - run: go mod download

      - name: Import GPG key
        id: import_gpg
        uses: hashicorp/ghaction-import-gpg@78437f97569a473e42b227be84d4084c2dfb49ba # v2.1.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSWORD }}

      - uses: goreleaser/goreleaser-action@68acf3b1adf004ac9c2f0a4259e85c5f66e99bef # v2.9.1
        with:
          version: latest
          args: release --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
